### ISSUE TITLE
Create a new project - Vert.x CRUD - fails

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio-vertx-boosters/vertx-crud-booster#6]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1667

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by gastaldi** [comment]
This can be closed, as Vert.x CRUD is no longer an approved OSIO quickstart and has been removed from the catalog

**Comment by cescoffier** [comment]
Closing.
